//! Catálogo de emojis Unicode del selector del compositor
//! (`ui::compose_menus::show_emoji_picker`).
//!
//! Es una lista curada (los emojis más usados, agrupados como en el cliente
//! real), no la tabla Unicode completa. Cada emoji lleva palabras clave en
//! español (y alguna en inglés) para el buscador — SIN tildes y en minúsculas,
//! porque `compose_menus::fold` normaliza lo que se tipea de la misma forma.
//! Los que por defecto se dibujan como texto (❤, ✌, ⚠…) ya traen su selector
//! de variación `U+FE0F`, igual que el resto de los emojis del selector.
//!
//! Se dibujan a color con `ui::emoji` (Twemoji), así que todos tienen que
//! existir ahí: por eso nada más nuevo que Unicode 13.

/// (título de la sección, emoji que la representa en la barra de arriba,
/// [(emoji, palabras clave)]).
pub type Category = (&'static str, &'static str, &'static [(&'static str, &'static str)]);

pub const CATEGORIES: &[Category] = &[
    ("CARAS", "😀", &[
        ("😀", "sonrisa feliz cara smile grin"),
        ("😃", "feliz ojos grandes alegre"),
        ("😄", "risa alegre contento"),
        ("😁", "sonriente dientes"),
        ("😆", "risa fuerte"),
        ("😅", "risa nerviosa sudor"),
        ("🤣", "carcajada rodando de risa lol"),
        ("😂", "lagrimas de risa jaja lol"),
        ("🙂", "sonrisa leve"),
        ("🙃", "al reves ironia"),
        ("😉", "guino"),
        ("😊", "sonrojado timido"),
        ("😇", "angel inocente"),
        ("🥰", "enamorado corazones carino"),
        ("😍", "ojos de corazon enamorado"),
        ("🤩", "estrellas ojos wow"),
        ("😘", "beso tirando beso"),
        ("😋", "rico sabroso"),
        ("😛", "lengua"),
        ("😜", "lengua guino loco"),
        ("🤪", "loco alocado"),
        ("😝", "lengua ojos cerrados"),
        ("🤑", "dinero plata"),
        ("🤗", "abrazo"),
        ("🤭", "risita mano boca"),
        ("🤫", "silencio shh"),
        ("🤔", "pensando duda hmm"),
        ("🤐", "boca cerrada cremallera"),
        ("🤨", "ceja levantada duda sospecha"),
        ("😐", "neutral"),
        ("😑", "sin expresion"),
        ("😶", "sin boca mudo"),
        ("😏", "picaro sonrisa de lado"),
        ("😒", "fastidio aburrido"),
        ("🙄", "ojos en blanco fastidio"),
        ("😬", "mueca nervioso"),
        ("😌", "aliviado tranquilo"),
        ("😔", "pensativo triste"),
        ("😪", "sueno cansado"),
        ("😴", "durmiendo sueno zzz"),
        ("😷", "barbijo mascarilla enfermo"),
        ("🤒", "fiebre enfermo termometro"),
        ("🤕", "herido venda"),
        ("🤢", "nauseas asco"),
        ("🤮", "vomito asco"),
        ("🥵", "calor acalorado"),
        ("🥶", "frio congelado"),
        ("🥴", "mareado borracho"),
        ("😵", "mareo"),
        ("🤯", "mente explota"),
        ("🤠", "vaquero"),
        ("🥳", "fiesta cumpleanos festejo"),
        ("😎", "lentes cool"),
        ("🤓", "nerd"),
        ("🧐", "monoculo"),
        ("😕", "confundido"),
        ("😟", "preocupado"),
        ("🙁", "triste"),
        ("😮", "sorpresa boca abierta"),
        ("😲", "asombrado"),
        ("😳", "sonrojo verguenza"),
        ("🥺", "ojitos suplicantes porfa"),
        ("😨", "miedo"),
        ("😰", "ansiedad sudor frio"),
        ("😢", "lagrima triste"),
        ("😭", "llorando"),
        ("😱", "grito miedo"),
        ("😞", "decepcionado"),
        ("😩", "cansado harto"),
        ("😫", "agotado"),
        ("🥱", "bostezo aburrido"),
        ("😤", "enojado resoplido"),
        ("😡", "enojado furioso"),
        ("😠", "enfadado"),
        ("🤬", "insultos"),
        ("😈", "diablito"),
        ("👿", "demonio"),
        ("💀", "calavera muerto"),
        ("☠️", "calavera huesos"),
        ("💩", "caca"),
        ("🤡", "payaso"),
        ("👻", "fantasma"),
        ("👽", "alien extraterrestre"),
        ("🤖", "robot"),
    ]),
    ("GESTOS", "👋", &[
        ("👍", "pulgar arriba like bien ok"),
        ("👎", "pulgar abajo dislike mal"),
        ("👌", "ok perfecto"),
        ("✌️", "paz victoria"),
        ("🤞", "dedos cruzados suerte"),
        ("🤟", "te quiero"),
        ("🤘", "rock"),
        ("🤙", "llamame"),
        ("👈", "izquierda senalar"),
        ("👉", "derecha senalar"),
        ("👆", "arriba senalar"),
        ("👇", "abajo senalar"),
        ("☝️", "uno arriba"),
        ("✋", "mano alto stop"),
        ("🖖", "vulcano spock"),
        ("👋", "saludo hola chau"),
        ("🤝", "apreton de manos trato"),
        ("👏", "aplausos"),
        ("🙌", "manos arriba celebrar"),
        ("👐", "manos abiertas"),
        ("🙏", "gracias por favor rezar"),
        ("✍️", "escribir"),
        ("💪", "fuerza musculo"),
        ("🧠", "cerebro"),
        ("👀", "ojos mirando"),
        ("👅", "lengua"),
        ("👄", "boca"),
        ("🤷", "no se encogerse de hombros"),
        ("🤦", "facepalm"),
        ("🙋", "levantar la mano"),
        ("💃", "bailar baile"),
        ("🕺", "bailar baile"),
    ]),
    ("CORAZONES", "❤️", &[
        ("❤️", "corazon rojo amor"),
        ("🧡", "corazon naranja"),
        ("💛", "corazon amarillo"),
        ("💚", "corazon verde"),
        ("💙", "corazon azul"),
        ("💜", "corazon violeta"),
        ("🖤", "corazon negro"),
        ("🤍", "corazon blanco"),
        ("🤎", "corazon marron"),
        ("💔", "corazon roto"),
        ("❣️", "exclamacion corazon"),
        ("💕", "dos corazones"),
        ("💞", "corazones girando"),
        ("💓", "corazon latiendo"),
        ("💗", "corazon creciendo"),
        ("💖", "corazon brillante"),
        ("💘", "corazon flecha"),
        ("💝", "corazon mono regalo"),
        ("💋", "beso labios"),
        ("💯", "cien perfecto"),
        ("💥", "explosion"),
        ("💫", "mareo estrellas"),
        ("💦", "gotas agua"),
        ("💤", "dormir zzz"),
    ]),
    ("ANIMALES Y NATURALEZA", "🐶", &[
        ("🐶", "perro"),
        ("🐱", "gato"),
        ("🐭", "raton"),
        ("🐹", "hamster"),
        ("🐰", "conejo"),
        ("🦊", "zorro"),
        ("🐻", "oso"),
        ("🐼", "panda"),
        ("🐨", "koala"),
        ("🐯", "tigre"),
        ("🦁", "leon"),
        ("🐮", "vaca"),
        ("🐷", "cerdo chancho"),
        ("🐸", "rana sapo"),
        ("🐵", "mono"),
        ("🙈", "no ver mono"),
        ("🙉", "no oir mono"),
        ("🙊", "no hablar mono"),
        ("🐔", "gallina pollo"),
        ("🐧", "pinguino"),
        ("🐦", "pajaro"),
        ("🦆", "pato"),
        ("🦅", "aguila"),
        ("🦉", "buho"),
        ("🐺", "lobo"),
        ("🐴", "caballo"),
        ("🦄", "unicornio"),
        ("🐝", "abeja"),
        ("🦋", "mariposa"),
        ("🐢", "tortuga"),
        ("🐍", "serpiente vibora"),
        ("🐙", "pulpo"),
        ("🐬", "delfin"),
        ("🐳", "ballena"),
        ("🦈", "tiburon"),
        ("🐊", "cocodrilo yacare"),
        ("🌸", "flor de cerezo"),
        ("🌹", "rosa"),
        ("🌻", "girasol"),
        ("🌲", "arbol pino"),
        ("🌴", "palmera"),
        ("🍀", "trebol suerte"),
        ("🌵", "cactus"),
        ("🍁", "hoja otono"),
    ]),
    ("COMIDA Y BEBIDA", "🍔", &[
        ("🍎", "manzana"),
        ("🍌", "banana"),
        ("🍇", "uvas"),
        ("🍓", "frutilla fresa"),
        ("🍉", "sandia"),
        ("🍍", "anana pina"),
        ("🥑", "palta aguacate"),
        ("🍅", "tomate"),
        ("🥕", "zanahoria"),
        ("🌽", "choclo maiz"),
        ("🥔", "papa patata"),
        ("🧀", "queso"),
        ("🍔", "hamburguesa"),
        ("🍟", "papas fritas"),
        ("🍕", "pizza"),
        ("🌭", "pancho hot dog"),
        ("🌮", "taco"),
        ("🥪", "sandwich"),
        ("🍝", "pasta fideos"),
        ("🍣", "sushi"),
        ("🍜", "ramen fideos"),
        ("🍿", "pochoclo palomitas"),
        ("🥟", "empanada"),
        ("🥩", "carne asado"),
        ("🍖", "carne hueso"),
        ("🍗", "pollo muslo"),
        ("🍩", "dona"),
        ("🍪", "galleta"),
        ("🎂", "torta cumpleanos"),
        ("🍰", "pastel"),
        ("🍫", "chocolate"),
        ("🍦", "helado"),
        ("🍺", "cerveza"),
        ("🍻", "brindis cervezas"),
        ("🍷", "vino"),
        ("🥂", "copas brindis"),
        ("🍸", "coctel trago"),
        ("🧉", "mate terere"),
        ("☕", "cafe"),
        ("🍵", "te"),
        ("🥤", "gaseosa vaso"),
        ("💧", "agua gota"),
    ]),
    ("ACTIVIDADES", "⚽", &[
        ("⚽", "futbol pelota"),
        ("🏀", "basquet"),
        ("🏈", "futbol americano"),
        ("⚾", "beisbol"),
        ("🎾", "tenis"),
        ("🏐", "voley"),
        ("🎱", "pool billar"),
        ("🏓", "ping pong"),
        ("🥊", "boxeo"),
        ("🎮", "videojuegos control gaming"),
        ("🕹️", "joystick"),
        ("🎲", "dado"),
        ("🧩", "rompecabezas puzzle"),
        ("🎯", "diana punteria"),
        ("🎳", "bowling"),
        ("🎸", "guitarra"),
        ("🎹", "piano"),
        ("🥁", "bateria"),
        ("🎤", "microfono"),
        ("🎧", "auriculares musica"),
        ("🎵", "nota musical"),
        ("🎶", "notas musicales"),
        ("🎬", "cine claqueta"),
        ("🎨", "arte paleta pintura"),
        ("🏆", "trofeo campeon"),
        ("🥇", "medalla oro primero"),
        ("🥈", "medalla plata"),
        ("🥉", "medalla bronce"),
        ("🎉", "fiesta confeti"),
        ("🎊", "confeti"),
        ("🎈", "globo"),
        ("🎁", "regalo"),
        ("🎃", "calabaza halloween"),
        ("🎄", "arbol de navidad"),
    ]),
    ("VIAJES Y CLIMA", "✈️", &[
        ("🚗", "auto"),
        ("🚕", "taxi"),
        ("🚌", "bus colectivo"),
        ("🏎️", "auto de carrera"),
        ("🚓", "policia"),
        ("🚑", "ambulancia"),
        ("🚒", "bomberos"),
        ("🚲", "bicicleta"),
        ("🏍️", "moto"),
        ("✈️", "avion"),
        ("🚀", "cohete"),
        ("🛸", "ovni"),
        ("🚁", "helicoptero"),
        ("⛵", "velero"),
        ("🚢", "barco"),
        ("🚂", "tren"),
        ("🏠", "casa hogar"),
        ("🏢", "edificio"),
        ("🏖️", "playa"),
        ("🌍", "mundo tierra"),
        ("🌙", "luna"),
        ("☀️", "sol"),
        ("⭐", "estrella"),
        ("🌟", "estrella brillante"),
        ("⚡", "rayo electricidad"),
        ("🔥", "fuego"),
        ("🌈", "arcoiris"),
        ("☁️", "nube"),
        ("❄️", "nieve copo"),
        ("⛄", "muneco de nieve"),
        ("🌧️", "lluvia"),
        ("🌪️", "tornado"),
    ]),
    ("OBJETOS", "💡", &[
        ("💻", "computadora laptop notebook"),
        ("🖥️", "pc monitor"),
        ("⌨️", "teclado"),
        ("🖱️", "mouse raton"),
        ("📱", "celular telefono"),
        ("📷", "camara foto"),
        ("💡", "idea lampara"),
        ("🔋", "bateria"),
        ("🔌", "enchufe"),
        ("💰", "dinero bolsa plata"),
        ("💵", "billete dolar"),
        ("💳", "tarjeta"),
        ("📈", "grafico sube"),
        ("📉", "grafico baja"),
        ("📌", "chincheta"),
        ("📎", "clip"),
        ("✏️", "lapiz"),
        ("📝", "nota memo"),
        ("📚", "libros"),
        ("📖", "libro abierto"),
        ("🔑", "llave"),
        ("🔒", "candado"),
        ("🔔", "campana notificacion"),
        ("🔕", "silencio campana"),
        ("⏰", "alarma reloj"),
        ("⌛", "reloj de arena"),
        ("🛠️", "herramientas"),
        ("🔧", "llave inglesa"),
        ("⚙️", "engranaje config"),
        ("🧲", "iman"),
        ("💣", "bomba"),
        ("🔮", "bola de cristal"),
        ("🧪", "probeta"),
        ("💊", "pastilla"),
        ("🛒", "carrito de compras"),
        ("🎒", "mochila"),
        ("👑", "corona rey"),
        ("💎", "diamante gema"),
        ("💍", "anillo"),
        ("👕", "remera camiseta"),
        ("👟", "zapatillas"),
        ("🕶️", "lentes de sol"),
    ]),
    ("SIMBOLOS", "✅", &[
        ("✅", "check ok listo"),
        ("❌", "equis cruz no"),
        ("❎", "equis verde"),
        ("⭕", "circulo rojo"),
        ("❗", "exclamacion"),
        ("❓", "pregunta"),
        ("‼️", "doble exclamacion"),
        ("⁉️", "exclamacion pregunta"),
        ("⚠️", "advertencia cuidado"),
        ("🚫", "prohibido"),
        ("✔️", "tilde"),
        ("➕", "mas suma"),
        ("➖", "menos resta"),
        ("➡️", "flecha derecha"),
        ("⬅️", "flecha izquierda"),
        ("⬆️", "flecha arriba"),
        ("⬇️", "flecha abajo"),
        ("🔄", "recargar actualizar"),
        ("🔁", "repetir"),
        ("🔀", "mezclar aleatorio"),
        ("▶️", "play reproducir"),
        ("⏸️", "pausa"),
        ("⏹️", "stop detener"),
        ("⏭️", "siguiente"),
        ("🔊", "volumen alto"),
        ("🔇", "silenciado mute"),
        ("🆗", "ok"),
        ("🆕", "nuevo"),
        ("🆒", "cool"),
        ("🔴", "circulo rojo"),
        ("🟠", "circulo naranja"),
        ("🟡", "circulo amarillo"),
        ("🟢", "circulo verde"),
        ("🔵", "circulo azul"),
        ("🟣", "circulo violeta"),
        ("⚫", "circulo negro"),
        ("⚪", "circulo blanco"),
        ("♻️", "reciclar"),
    ]),
    ("BANDERAS", "🏁", &[
        ("🇵🇾", "paraguay bandera"),
        ("🇦🇷", "argentina bandera"),
        ("🇧🇷", "brasil bandera"),
        ("🇺🇾", "uruguay bandera"),
        ("🇨🇱", "chile bandera"),
        ("🇧🇴", "bolivia bandera"),
        ("🇵🇪", "peru bandera"),
        ("🇨🇴", "colombia bandera"),
        ("🇪🇨", "ecuador bandera"),
        ("🇻🇪", "venezuela bandera"),
        ("🇲🇽", "mexico bandera"),
        ("🇪🇸", "espana bandera"),
        ("🇺🇸", "estados unidos eeuu bandera"),
        ("🇬🇧", "reino unido bandera"),
        ("🇫🇷", "francia bandera"),
        ("🇩🇪", "alemania bandera"),
        ("🇮🇹", "italia bandera"),
        ("🇯🇵", "japon bandera"),
        ("🏁", "meta carrera bandera"),
        ("🚩", "bandera roja"),
        ("🏳️‍🌈", "orgullo arcoiris bandera"),
        ("🏴‍☠️", "pirata bandera"),
    ]),
];
